#!/usr/bin/env python3
import os
import pickle

from sklearn.linear_model import LogisticRegression

prefix = '/opt/ml/'
input_path = os.path.join(prefix, 'input')
data_path = os.path.join(input_path, 'data')
model_path = os.path.join(prefix, 'model')

channel_name = 'training'
data_path = os.path.join(data_path, channel_name)

if __name__ == '__main__':
    # Load data
    train_path = os.path.join(data_path, 'train_data.pkl')
    train_x, train_y = pickle.load(open(train_path, 'rb'))

    # Train
    model = LogisticRegression(C=1e5, solver='lbfgs', multi_class='multinomial')
    model.fit(train_x, train_y)

    # Save
    save_path = os.path.join(model_path, 'model.pkl')
    pickle.dump(model, open(save_path, 'wb'))
